/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { GetPresignedUrlResponse } from "../models/index";
import {
  GetPresignedUrlResponseFromJSON,
  GetPresignedUrlResponseToJSON,
} from "../models/index";

export interface GetPresignedUrlRequest {
  bucket: string;
  key: string;
}

/**
 * MinioApi - interface
 *
 * @export
 * @interface MinioApiInterface
 */
export interface MinioApiInterface {
  /**
   * Get a presigned url
   * @summary
   * @param {string} bucket
   * @param {string} key
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MinioApiInterface
   */
  getPresignedUrlRaw(
    requestParameters: GetPresignedUrlRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetPresignedUrlResponse>>;

  /**
   * Get a presigned url
   *
   */
  getPresignedUrl(
    requestParameters: GetPresignedUrlRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetPresignedUrlResponse>;
}

/**
 *
 */
export class MinioApi extends runtime.BaseAPI implements MinioApiInterface {
  /**
   * Get a presigned url
   *
   */
  async getPresignedUrlRaw(
    requestParameters: GetPresignedUrlRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetPresignedUrlResponse>> {
    if (requestParameters["bucket"] == null) {
      throw new runtime.RequiredError(
        "bucket",
        'Required parameter "bucket" was null or undefined when calling getPresignedUrl().',
      );
    }

    if (requestParameters["key"] == null) {
      throw new runtime.RequiredError(
        "key",
        'Required parameter "key" was null or undefined when calling getPresignedUrl().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["bucket"] != null) {
      queryParameters["bucket"] = requestParameters["bucket"];
    }

    if (requestParameters["key"] != null) {
      queryParameters["key"] = requestParameters["key"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/minio/get-presigned-url`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetPresignedUrlResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get a presigned url
   *
   */
  async getPresignedUrl(
    requestParameters: GetPresignedUrlRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetPresignedUrlResponse> {
    const response = await this.getPresignedUrlRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
