/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProductRequest,
  MessageResponse,
  ProductResponse,
  UpdateProductRequest,
} from '../models/index';
import {
    CreateProductRequestFromJSON,
    CreateProductRequestToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    ProductResponseFromJSON,
    ProductResponseToJSON,
    UpdateProductRequestFromJSON,
    UpdateProductRequestToJSON,
} from '../models/index';

export interface ProductControllerCreateProductRequest {
    createProductRequest: CreateProductRequest;
}

export interface ProductControllerDeleteProductByIdRequest {
    id: string;
}

export interface ProductControllerGetAllProductsRequest {
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface ProductControllerGetProductByIdRequest {
    id: string;
}

export interface ProductControllerUpdateProductByIdRequest {
    id: string;
    updateProductRequest: UpdateProductRequest;
}

/**
 * ProductApi - interface
 * 
 * @export
 * @interface ProductApiInterface
 */
export interface ProductApiInterface {
    /**
     * 
     * @param {CreateProductRequest} createProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    productControllerCreateProductRaw(requestParameters: ProductControllerCreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponse>>;

    /**
     */
    productControllerCreateProduct(requestParameters: ProductControllerCreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponse>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    productControllerDeleteProductByIdRaw(requestParameters: ProductControllerDeleteProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>>;

    /**
     */
    productControllerDeleteProductById(requestParameters: ProductControllerDeleteProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse>;

    /**
     * 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string} [search] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    productControllerGetAllProductsRaw(requestParameters: ProductControllerGetAllProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    productControllerGetAllProducts(requestParameters: ProductControllerGetAllProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    productControllerGetProductByIdRaw(requestParameters: ProductControllerGetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponse>>;

    /**
     */
    productControllerGetProductById(requestParameters: ProductControllerGetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponse>;

    /**
     * 
     * @param {string} id 
     * @param {UpdateProductRequest} updateProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductApiInterface
     */
    productControllerUpdateProductByIdRaw(requestParameters: ProductControllerUpdateProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponse>>;

    /**
     */
    productControllerUpdateProductById(requestParameters: ProductControllerUpdateProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponse>;

}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI implements ProductApiInterface {

    /**
     */
    async productControllerCreateProductRaw(requestParameters: ProductControllerCreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponse>> {
        if (requestParameters['createProductRequest'] == null) {
            throw new runtime.RequiredError(
                'createProductRequest',
                'Required parameter "createProductRequest" was null or undefined when calling productControllerCreateProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/product`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductRequestToJSON(requestParameters['createProductRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseFromJSON(jsonValue));
    }

    /**
     */
    async productControllerCreateProduct(requestParameters: ProductControllerCreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponse> {
        const response = await this.productControllerCreateProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productControllerDeleteProductByIdRaw(requestParameters: ProductControllerDeleteProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling productControllerDeleteProductById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/product/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async productControllerDeleteProductById(requestParameters: ProductControllerDeleteProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.productControllerDeleteProductByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productControllerGetAllProductsRaw(requestParameters: ProductControllerGetAllProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/product`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async productControllerGetAllProducts(requestParameters: ProductControllerGetAllProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.productControllerGetAllProductsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async productControllerGetProductByIdRaw(requestParameters: ProductControllerGetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling productControllerGetProductById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/product/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseFromJSON(jsonValue));
    }

    /**
     */
    async productControllerGetProductById(requestParameters: ProductControllerGetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponse> {
        const response = await this.productControllerGetProductByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productControllerUpdateProductByIdRaw(requestParameters: ProductControllerUpdateProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling productControllerUpdateProductById().'
            );
        }

        if (requestParameters['updateProductRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProductRequest',
                'Required parameter "updateProductRequest" was null or undefined when calling productControllerUpdateProductById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/product/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProductRequestToJSON(requestParameters['updateProductRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseFromJSON(jsonValue));
    }

    /**
     */
    async productControllerUpdateProductById(requestParameters: ProductControllerUpdateProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponse> {
        const response = await this.productControllerUpdateProductByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
