FROM node:20-alpine AS builder

WORKDIR /app

COPY ./server .

RUN npm install -g @nestjs/cli
RUN npm install --omit=dev

RUN npm run build:api

FROM node:20-alpine AS production

WORKDIR /app

COPY ./server/package.json ./

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/apps/api/src/main"]
