/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductRequest
 */
export interface CreateProductRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateProductRequest
     */
    images: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequest
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequest
     */
    discountPrice: number | null;
}

/**
 * Check if a given object implements the CreateProductRequest interface.
 */
export function instanceOfCreateProductRequest(value: object): value is CreateProductRequest {
    if (!('images' in value) || value['images'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('discountPrice' in value) || value['discountPrice'] === undefined) return false;
    return true;
}

export function CreateProductRequestFromJSON(json: any): CreateProductRequest {
    return CreateProductRequestFromJSONTyped(json, false);
}

export function CreateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'],
        'name': json['name'],
        'description': json['description'],
        'price': json['price'],
        'discountPrice': json['discountPrice'],
    };
}

export function CreateProductRequestToJSON(json: any): CreateProductRequest {
    return CreateProductRequestToJSONTyped(json, false);
}

export function CreateProductRequestToJSONTyped(value?: CreateProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': value['images'],
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'discountPrice': value['discountPrice'],
    };
}

