/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPresignedUrlResponse
 */
export interface GetPresignedUrlResponse {
    /**
     * 
     * @type {string}
     * @memberof GetPresignedUrlResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetPresignedUrlResponse
     */
    presignedUrl: string;
    /**
     * 
     * @type {string}
     * @memberof GetPresignedUrlResponse
     */
    previewUrl: string;
}

/**
 * Check if a given object implements the GetPresignedUrlResponse interface.
 */
export function instanceOfGetPresignedUrlResponse(value: object): value is GetPresignedUrlResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('presignedUrl' in value) || value['presignedUrl'] === undefined) return false;
    if (!('previewUrl' in value) || value['previewUrl'] === undefined) return false;
    return true;
}

export function GetPresignedUrlResponseFromJSON(json: any): GetPresignedUrlResponse {
    return GetPresignedUrlResponseFromJSONTyped(json, false);
}

export function GetPresignedUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPresignedUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'presignedUrl': json['presignedUrl'],
        'previewUrl': json['previewUrl'],
    };
}

export function GetPresignedUrlResponseToJSON(json: any): GetPresignedUrlResponse {
    return GetPresignedUrlResponseToJSONTyped(json, false);
}

export function GetPresignedUrlResponseToJSONTyped(value?: GetPresignedUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'presignedUrl': value['presignedUrl'],
        'previewUrl': value['previewUrl'],
    };
}

