/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
  /**
   *
   * @type {string}
   * @memberof ProductResponse
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ProductResponse
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductResponse
   */
  images: Array<string>;
  /**
   *
   * @type {string}
   * @memberof ProductResponse
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof ProductResponse
   */
  price: number;
  /**
   *
   * @type {number}
   * @memberof ProductResponse
   */
  discountPrice: number | null;
  /**
   *
   * @type {Date}
   * @memberof ProductResponse
   */
  createdAtUtc: Date;
  /**
   *
   * @type {Date}
   * @memberof ProductResponse
   */
  updatedAtUtc: Date;
}

/**
 * Check if a given object implements the ProductResponse interface.
 */
export function instanceOfProductResponse(
  value: object,
): value is ProductResponse {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("images" in value) || value["images"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("price" in value) || value["price"] === undefined) return false;
  if (!("discountPrice" in value) || value["discountPrice"] === undefined)
    return false;
  if (!("createdAtUtc" in value) || value["createdAtUtc"] === undefined)
    return false;
  if (!("updatedAtUtc" in value) || value["updatedAtUtc"] === undefined)
    return false;
  return true;
}

export function ProductResponseFromJSON(json: any): ProductResponse {
  return ProductResponseFromJSONTyped(json, false);
}

export function ProductResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProductResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    images: json["images"],
    description: json["description"],
    price: json["price"],
    discountPrice: json["discountPrice"],
    createdAtUtc: new Date(json["createdAtUtc"]),
    updatedAtUtc: new Date(json["updatedAtUtc"]),
  };
}

export function ProductResponseToJSON(json: any): ProductResponse {
  return ProductResponseToJSONTyped(json, false);
}

export function ProductResponseToJSONTyped(
  value?: ProductResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    images: value["images"],
    description: value["description"],
    price: value["price"],
    discountPrice: value["discountPrice"],
    createdAtUtc: value["createdAtUtc"].toISOString(),
    updatedAtUtc: value["updatedAtUtc"].toISOString(),
  };
}
