/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateProductRequest
 */
export interface UpdateProductRequest {
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateProductRequest
   */
  images: Array<string>;
  /**
   *
   * @type {string}
   * @memberof UpdateProductRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UpdateProductRequest
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof UpdateProductRequest
   */
  price: number;
  /**
   *
   * @type {number}
   * @memberof UpdateProductRequest
   */
  discountPrice: number | null;
}

/**
 * Check if a given object implements the UpdateProductRequest interface.
 */
export function instanceOfUpdateProductRequest(
  value: object,
): value is UpdateProductRequest {
  if (!("images" in value) || value["images"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("price" in value) || value["price"] === undefined) return false;
  if (!("discountPrice" in value) || value["discountPrice"] === undefined)
    return false;
  return true;
}

export function UpdateProductRequestFromJSON(json: any): UpdateProductRequest {
  return UpdateProductRequestFromJSONTyped(json, false);
}

export function UpdateProductRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateProductRequest {
  if (json == null) {
    return json;
  }
  return {
    images: json["images"],
    name: json["name"],
    description: json["description"],
    price: json["price"],
    discountPrice: json["discountPrice"],
  };
}

export function UpdateProductRequestToJSON(json: any): UpdateProductRequest {
  return UpdateProductRequestToJSONTyped(json, false);
}

export function UpdateProductRequestToJSONTyped(
  value?: UpdateProductRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    images: value["images"],
    name: value["name"],
    description: value["description"],
    price: value["price"],
    discountPrice: value["discountPrice"],
  };
}
